spring.application.name=tradeOS

spring.datasource.url=jdbc:postgresql://localhost:5432/tradeos

spring.datasource.username=postgres

spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}

openrouter.api.key=${OPENROUTER_API_KEY}